"""Shared utility functions for text, safety, numeric and pose handling."""

from ._legacy import (
    clamp,
    safe_float,
    safe_int,
    mean_abs,
    normalize_text,
    has_any_token,
    contains_any,
    wrap_signed,
    wrap_abs,
    voice_vector,
    format_float,
    json_compatible,
    manipulator_rate_limits,
    clamp_manipulator_rate_vector,
    manipulator_rate_from_delta_hint,
    normalize_training_target,
    inference_dt_from_period_ms,
    clamp_member_pose,
    normalize_robot_name,
    resolve_active_robot_name,
    runtime_mode_label,
    pose_from_state,
    ui_pose_to_armj_values,
    build_armj_command,
    nudge_manipulator_pose,
)
